import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Interface for the image queries generated by Gemini
export interface PlaceImageQueries {
  heroQuery: string;
  popularPlaces: { name: string; query: string }[];
  nearby: { name: string; query: string }[];
}

// Interface for the final dynamic images
export interface DestinationDynamicImages {
  heroImage: string;
  popularPlaces: { name: string; image: string }[];
  nearby: { name: string; image: string }[];
}

/**
 * Returns a formatted Unsplash featured image URL
 */
export function getImageUrl(query: string) {
  // Using the user's requested 1600x900 format with the legacy source URL which works well for random keyword queries
  return `https://source.unsplash.com/1600x900/?${encodeURIComponent(query)}`;
}

/**
 * Uses Gemini to generate STRICT, descriptive image search queries for a location.
 * Every query MUST include the place name, city name, and a visual hint.
 */
export async function generatePlaceImageQueries(location: string): Promise<PlaceImageQueries> {
  const Schema = z.object({
    heroQuery: z.string(),
    popularPlaces: z.array(z.object({ name: z.string(), query: z.string() })),
    nearby: z.array(z.object({ name: z.string(), query: z.string() }))
  });

  try {
    const { output } = await ai.generate({
      prompt: `
Generate travel data for: ${location}

Return STRICT JSON:

{
  "heroQuery": "...",
  "popularPlaces": [
    { "name": "...", "query": "..." }
  ],
  "nearby": [
    { "name": "...", "query": "..." }
  ]
}

RULES:
- Each query MUST include:
  1. Place name
  2. City name (${location})
  3. Visual keywords (skyline, temple, beach, street, etc.)

GOOD EXAMPLES:
- "Chicago skyline night aerial view"
- "Millennium Park Chicago Cloud Gate"
- "Navy Pier Chicago ferris wheel lake"

BAD EXAMPLES:
- "nature"
- "travel"
- "mountains"

Return ONLY JSON.
`,
      output: { schema: Schema }
    });

    if (!output) throw new Error("Gemini failed to generate strict queries.");
    return output;
  } catch (error) {
    console.error("Gemini Strict Image Query Generation Error:", error);
    // Generic high-quality fallback that still includes the location
    return {
      heroQuery: `${location} city skyline aerial view 4k`,
      popularPlaces: [
        { name: "Main Attraction", query: `${location} famous landmark building high quality` }
      ],
      nearby: [
        { name: "Nearby Spot", query: `${location} region scenic travel view` }
      ]
    };
  }
}

/**
 * Full service to get real dynamic images for a location using Gemini + Unsplash with strict queries.
 */
export async function getDestinationImages(location: string): Promise<DestinationDynamicImages> {
  const queries = await generatePlaceImageQueries(location);
  
  return {
    heroImage: getImageUrl(queries.heroQuery),
    popularPlaces: queries.popularPlaces.map(p => ({
      name: p.name,
      image: getImageUrl(p.query)
    })),
    nearby: queries.nearby.map(n => ({
      name: n.name,
      image: getImageUrl(n.query)
    }))
  };
}
